// lib/models/civitai_image_model.dart

import 'package:featch_flow/models/unified_post_model.dart';
import 'package:featch_flow/utils/json_converters.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
// Import our single MediaType definition to avoid type conflicts.
// 导入我们唯一的 MediaType 定义，避免类型冲突。

part 'civitai_image_model.freezed.dart';
part 'civitai_image_model.g.dart';

// Define all nested models related to Civitai Image in this file using freezed for consistency.
// 将所有与 Civitai Image 相关的嵌套模型都定义在这个文件中，并使用 freezed 进行改造，确保一致性。

@freezed
class ImageStats with _$ImageStats {
  const factory ImageStats({
    @Default(0) int likeCount,
    // Additional stats like dislikeCount, cryCount, laughCount, commentCount can be added as needed.
    // 根据需要可以添加 dislikeCount, cryCount, laughCount, commentCount 等其他统计数据。
  }) = _ImageStats;

  factory ImageStats.fromJson(Map<String, dynamic> json) =>
      _$ImageStatsFromJson(json);
}

@freezed
class ImageMeta with _$ImageMeta {
  const factory ImageMeta({
    @JsonKey(name: 'prompt') String? prompt,
    @JsonKey(name: 'negativePrompt') String? negativePrompt,
    @JsonKey(name: 'tags') @Default(<String>[]) List<String>? tags,
  }) = _ImageMeta;

  factory ImageMeta.fromJson(Map<String, dynamic> json) =>
      _$ImageMetaFromJson(json);
}

// CivitaiImageModel rewritten to fully utilize freezed.
// 重写 CivitaiImageModel，完全拥抱 freezed。
@freezed
class CivitaiImageModel with _$CivitaiImageModel {
  // Private constructor to allow custom getters (e.g., thumbnailUrl).
  // 添加一个私有构造函数，以便我们可以添加自定义的 getter (thumbnailUrl)。
  const CivitaiImageModel._();

  const factory CivitaiImageModel({
    required int id,
    required String url,
    @ForceStringConverter() required String? hash,

    @Default(1024) int width,
    @Default(1024) int height,
    @Default(false) bool nsfw,
    @ForceStringConverter() String? username, // Author name from the API.
    @JsonKey(unknownEnumValue: MediaType.image) required MediaType type,
    ImageMeta? meta,
    ImageStats? stats,
  }) = _CivitaiImageModel;

  // This line of code replaces all your previous handwritten fromJson logic.
  // All field parsing, type conversion, and default value handling are automatically generated by build_runner.
  // 这一行代码，代替了您之前所有手写的 fromJson 逻辑。
  // 所有字段的解析、类型转换、默认值处理，都由 build_runner 自动生成。
  factory CivitaiImageModel.fromJson(Map<String, dynamic> json) =>
      _$CivitaiImageModelFromJson(json);

  // Your custom getter logic is excellent and will be retained.
  // freezed perfectly supports adding custom methods or getters to the class.
  // 您的自定义 getter 逻辑非常棒，我们将其保留。
  // freezed 完美支持在类中添加自定义方法或 getter。
  String get thumbnailUrl {
    // Optimization: if the URL already contains a width parameter, it might be a thumbnail.
    // 这是一个优化，如果 URL 已经包含宽度参数，可能它就是缩略图。
    if (url.contains('width=')) {
      return url;
    }

    if (type == MediaType.video) {
      // Video conversion logic.
      // 视频的转换逻辑。
      return url.replaceFirst(
        '/original=true',
        '/transcode=true,width=450,optimized=true',
      );
    } else {
      // Image/GIF conversion logic.
      // 图片/GIF的转换逻辑。
      return url.replaceFirst(
        '/original=true',
        '/anim=false,width=450,optimized=true',
      );
    }
  }
}
