// lib/models/unified_post_model.dart
// Import the freezed annotation package.
// 导入 freezed annotation 包。
import 'package:freezed_annotation/freezed_annotation.dart';

// Define the files to be created by the code generator.
// 定义代码生成器需要创建的文件。
part 'unified_post_model.freezed.dart'; // File generated by freezed.
part 'unified_post_model.g.dart'; // File generated by json_serializable.

// Previously defined enum.
// 之前定义的枚举。
enum MediaType { image, video, gif }

@freezed
class UnifiedPostModel with _$UnifiedPostModel {
  const factory UnifiedPostModel({
    // --- Core identity information ---
    // --- 核心身份信息 ---
    required String id,
    required String source,

    // --- Core media information ---
    // --- 核心媒体信息 ---
    required String previewImageUrl,
    required String fullImageUrl,
    required int width,
    required int height,
    required MediaType mediaType,

    // --- Additional information ---
    // --- 附加信息 ---
    @Default([]) List<String>? tags,
    String? author,
    int? score,

    // --- Metadata ---
    // --- 元数据 ---
    String? detailsUrl,
    @Default({}) Map<String, dynamic>? originalData,
  }) = _UnifiedPostModel;

  // Add a fromJson factory constructor to convert a Map to an object.
  // 添加 fromJson 工厂构造函数，以便将 Map 转换为对象。
  factory UnifiedPostModel.fromJson(Map<String, dynamic> json) =>
      _$UnifiedPostModelFromJson(json);
}
